### ISSUE TITLE
CNAB_AZURE_STATE_FILESHARE doesn't work?

### ISSUE THREAD

**Issue by hoangmnsd** [deislabs/cnab-azure-driver#44]
I passed these env variables to the ACI:  
CNAB_AZURE_STATE_FILESHARE  
CNAB_AZURE_STATE_STORAGE_ACCOUNT_NAME   
CNAB_AZURE_STATE_STORAGE_ACCOUNT_KEY  
CNAB_AZURE_STATE_PATH  

in porter.yaml I have configured outputs already:   
```yaml
outputs:
- name: kubeconfig
  type: string
  description: "Kubeconfig for the AKS cluster"
  sensitive: true
  applyTo:
    - "install"
    
    
install:
  - az: 
      description: "Azure CLI AKS get-credentials"
      arguments: 
        - "aks" 
        - "get-credentials" 
      flags:
        resource-group: "{{ bundle.parameters.resource_group }}"
        name: "{{ bundle.parameters.cluster_name }}"
        file: "/root/.kube/config"
      outputs:
        - name: kubeconfig
          path: /root/.kube/config
```

But in the Storage Account Fileshare, there are no file/content in it.

What is the problem, Does it work anymore?
